import 'package:app/generated/json/base/json_convert_content.dart';
import 'package:app/generated/json/base/json_filed.dart';

class LanguageEntity with JsonConvert<LanguageEntity> {
  @JSONField(name: "main_bottom_menu_home")
  String mainBottomMenuHome;
  @JSONField(name: "main_bottom_menu_concert")
  String mainBottomMenuConcert;
  @JSONField(name: "main_bottom_menu_ticket")
  String mainBottomMenuTicket;
  @JSONField(name: "main_bottom_menu_notifications")
  String mainBottomMenuNotifications;
  @JSONField(name: "main_bottom_menu_profile")
  String mainBottomMenuProfile;
  @JSONField(name: "common_confirm")
  String commonConfirm;
  @JSONField(name: "common_reject")
  String commonReject;
  @JSONField(name: "common_next")
  String commonNext;
  @JSONField(name: "common_cancel")
  String commonCancel;
  @JSONField(name: "common_search")
  String commonSearch;
  @JSONField(name: "common_empty")
  String commonEmpty;
  @JSONField(name: "common_yes")
  String commonYes;
  @JSONField(name: "common_no")
  String commonNo;
  @JSONField(name: "common_album")
  String commonAlbum;
  @JSONField(name: "common_remark")
  String commonRemark;
  @JSONField(name: "common_choose")
  String commonChoose;
  @JSONField(name: "login_phone_no_hint")
  String loginPhoneNoHint;
  @JSONField(name: "login_password_hint")
  String loginPasswordHint;
  @JSONField(name: "login_btn_submit")
  String loginBtnSubmit;
  @JSONField(name: "login_btn_register")
  String loginBtnRegister;
  @JSONField(name: "login_btn_forgot_password")
  String loginBtnForgotPassword;
  @JSONField(name: "login_btn_fb_title")
  String loginBtnFbTitle;
  @JSONField(name: "login_title_or")
  String loginTitleOr;
  @JSONField(name: "login_not_member_title")
  String loginNotMemberTitle;
  @JSONField(name: "login_not_member_signup_title")
  String loginNotMemberSignupTitle;
  @JSONField(name: "login_before_mobile_register_title")
  String loginBeforeMobileRegisterTitle;
  @JSONField(name: "register_header")
  String registerHeader;
  @JSONField(name: "register_input_phone_title")
  String registerInputPhoneTitle;
  @JSONField(name: "register_input_phone_hint")
  String registerInputPhoneHint;
  @JSONField(name: "register_otp_message")
  String registerOtpMessage;
  @JSONField(name: "register_accept")
  String registerAccept;
  @JSONField(name: "register_terms_and_conditions")
  String registerTermsAndConditions;
  @JSONField(name: "register_btn_confirm")
  String registerBtnConfirm;
  @JSONField(name: "channel_verification_title")
  String channelVerificationTitle;
  @JSONField(name: "channel_verification_sms")
  String channelVerificationSms;
  @JSONField(name: "channel_verification_voice_call")
  String channelVerificationVoiceCall;
  @JSONField(name: "confirm_otp_title")
  String confirmOtpTitle;
  @JSONField(name: "confirm_otp_message")
  String confirmOtpMessage;
  @JSONField(name: "confirm_otp_send_again")
  String confirmOtpSendAgain;
  @JSONField(name: "confirm_otp_waiting_send_again")
  String confirmOtpWaitingSendAgain;
  String second;
  @JSONField(name: "confirm_otp_reference")
  String confirmOtpReference;
  @JSONField(name: "user_info_header")
  String userInfoHeader;
  @JSONField(name: "user_info_firstname")
  String userInfoFirstname;
  @JSONField(name: "user_info_firstname_hint")
  String userInfoFirstnameHint;
  @JSONField(name: "user_info_lastname")
  String userInfoLastname;
  @JSONField(name: "user_info_lastname_hint")
  String userInfoLastnameHint;
  @JSONField(name: "user_info_gender")
  String userInfoGender;
  @JSONField(name: "user_info_birthday")
  String userInfoBirthday;
  @JSONField(name: "user_info_gender_hint")
  String userInfoGenderHint;
  @JSONField(name: "user_info_birthday_hint")
  String userInfoBirthdayHint;
  @JSONField(name: "user_info_alert_title")
  String userInfoAlertTitle;
  @JSONField(name: "create_password_header")
  String createPasswordHeader;
  @JSONField(name: "create_password_title")
  String createPasswordTitle;
  @JSONField(name: "create_password_help")
  String createPasswordHelp;
  @JSONField(name: "create_password_again_title")
  String createPasswordAgainTitle;
  @JSONField(name: "create_user_success_title")
  String createUserSuccessTitle;
  @JSONField(name: "create_user_success_start")
  String createUserSuccessStart;
  @JSONField(name: "forgot_password_title")
  String forgotPasswordTitle;
  @JSONField(name: "forgot_password_phone_no")
  String forgotPasswordPhoneNo;
  @JSONField(name: "forgot_password_phone_no_hint")
  String forgotPasswordPhoneNoHint;
  @JSONField(name: "forgot_password_message")
  String forgotPasswordMessage;
  String profile;
  @JSONField(name: "profile_title")
  String profileTitle;
  @JSONField(name: "profile_edit")
  String profileEdit;
  @JSONField(name: "profile_info")
  String profileInfo;
  @JSONField(name: "profile_setting")
  String profileSetting;
  @JSONField(name: "profile_help_center")
  String profileHelpCenter;
  @JSONField(name: "profile_contact_us")
  String profileContactUs;
  @JSONField(name: "profile_terms_of_service")
  String profileTermsOfService;
  @JSONField(name: "profile_privacy_policy")
  String profilePrivacyPolicy;
  @JSONField(name: "setting_title")
  String settingTitle;
  @JSONField(name: "setting_edit_profile")
  String settingEditProfile;
  @JSONField(name: "setting_notification")
  String settingNotification;
  @JSONField(name: "setting_change_language")
  String settingChangeLanguage;
  @JSONField(name: "setting_change_password")
  String settingChangePassword;
  @JSONField(name: "setting_logout")
  String settingLogout;
  @JSONField(name: "setting_current_version")
  String settingCurrentVersion;
  @JSONField(name: "edit_profile_title")
  String editProfileTitle;
  @JSONField(name: "edit_profile_phone_no")
  String editProfilePhoneNo;
  @JSONField(name: "edit_profile_name")
  String editProfileName;
  @JSONField(name: "edit_profile_name_hint")
  String editProfileNameHint;
  @JSONField(name: "edit_profile_last_name")
  String editProfileLastName;
  @JSONField(name: "edit_profile_last_name_hint")
  String editProfileLastNameHint;
  @JSONField(name: "edit_profile_birthday")
  String editProfileBirthday;
  @JSONField(name: "edit_profile_choose_birth_date")
  String editProfileChooseBirthDate;
  @JSONField(name: "edit_profile_gender")
  String editProfileGender;
  @JSONField(name: "edit_profile_select_gender")
  String editProfileSelectGender;
  @JSONField(name: "edit_profile_save")
  String editProfileSave;
  @JSONField(name: "edit_profile_photo_camera_error_message")
  String editProfilePhotoCameraErrorMessage;
  @JSONField(name: "edit_profile_photo_library_error_message")
  String editProfilePhotoLibraryErrorMessage;
  @JSONField(name: "gender_dialog_title")
  String genderDialogTitle;
  @JSONField(name: "gender_dialog_male")
  String genderDialogMale;
  @JSONField(name: "gender_dialog_female")
  String genderDialogFemale;
  @JSONField(name: "gender_dialog_everyone")
  String genderDialogEveryone;
  @JSONField(name: "gender_dialog_not_specified")
  String genderDialogNotSpecified;
  @JSONField(name: "change_password_title")
  String changePasswordTitle;
  @JSONField(name: "change_password_old_password")
  String changePasswordOldPassword;
  @JSONField(name: "change_password_old_password_hint")
  String changePasswordOldPasswordHint;
  @JSONField(name: "change_password_new_password")
  String changePasswordNewPassword;
  @JSONField(name: "change_password_new_password_hint")
  String changePasswordNewPasswordHint;
  @JSONField(name: "change_password_new_password_help")
  String changePasswordNewPasswordHelp;
  @JSONField(name: "change_password_new_password_again")
  String changePasswordNewPasswordAgain;
  @JSONField(name: "error_dialog")
  String errorDialog;
  @JSONField(name: "action_sheet_camera")
  String actionSheetCamera;
  @JSONField(name: "action_sheet_photo_library")
  String actionSheetPhotoLibrary;
  @JSONField(name: "action_sheet_profile_image")
  String actionSheetProfileImage;
  @JSONField(name: "action_cancel")
  String actionCancel;
  @JSONField(name: "order_list_order_date")
  String orderListOrderDate;
  @JSONField(name: "order_detail")
  String orderDetail;
  @JSONField(name: "order_detail_order_no")
  String orderDetailOrderNo;
  @JSONField(name: "order_detail_date")
  String orderDetailDate;
  @JSONField(name: "order_detail_total")
  String orderDetailTotal;
  @JSONField(name: "order_detail_see_detail")
  String orderDetailSeeDetail;
  @JSONField(name: "order_detail_see_ticket")
  String orderDetailSeeTicket;
  @JSONField(name: "order_detail_payment_type")
  String orderDetailPaymentType;
  @JSONField(name: "order_detail_or")
  String orderDetailOr;
  @JSONField(name: "order_detail_print")
  String orderDetailPrint;
  @JSONField(name: "order_detail_unsuccess")
  String orderDetailUnsuccess;
  @JSONField(name: "order_detail_show_barcode")
  String orderDetailShowBarcode;
  @JSONField(name: "order_detail_time_remaining")
  String orderDetailTimeRemaining;
  @JSONField(name: "order_detail_pay_within")
  String orderDetailPayWithin;
  @JSONField(name: "order_detail_place_order_again")
  String orderDetailPlaceOrderAgain;
  @JSONField(name: "order_detail_already_paid")
  String orderDetailAlreadyPaid;
  @JSONField(name: "order_detail_wait_for_payment")
  String orderDetailWaitForPayment;
  @JSONField(name: "order_detail_expired")
  String orderDetailExpired;
  @JSONField(name: "order_detail_show_barcode_button")
  String orderDetailShowBarcodeButton;
  @JSONField(name: "order_detail_upload_slip_button_title")
  String orderDetailUploadSlipButtonTitle;
  @JSONField(name: "order_detail_upload_slip_document_status_title")
  String orderDetailUploadSlipDocumentStatusTitle;
  @JSONField(name: "order_detail_upload_slip_document_button")
  String orderDetailUploadSlipDocumentButton;
  @JSONField(name: "order_detail_document_status_title")
  String orderDetailDocumentStatusTitle;
  @JSONField(name: "order_detail_upload_back_dialog")
  String orderDetailUploadBackDialog;
  @JSONField(name: "order_list_payment_again")
  String orderListPaymentAgain;
  @JSONField(name: "order_list_payment_count_down_label")
  String orderListPaymentCountDownLabel;
  @JSONField(name: "order_detail_change_payment_button")
  String orderDetailChangePaymentButton;
  @JSONField(name: "news_header")
  String newsHeader;
  @JSONField(name: "news_detail_share")
  String newsDetailShare;
  @JSONField(name: "friend_header")
  String friendHeader;
  @JSONField(name: "friend_info_age")
  String friendInfoAge;
  @JSONField(name: "friend_info_weight")
  String friendInfoWeight;
  @JSONField(name: "friend_info_height")
  String friendInfoHeight;
  @JSONField(name: "friend_info_chest")
  String friendInfoChest;
  @JSONField(name: "friend_info_waist")
  String friendInfoWaist;
  @JSONField(name: "friend_info_hip")
  String friendInfoHip;
  @JSONField(name: "friend_book_now_title")
  String friendBookNowTitle;
  @JSONField(name: "booking_header")
  String bookingHeader;
  @JSONField(name: "booking_detail_title")
  String bookingDetailTitle;
  @JSONField(name: "country_select_title")
  String countrySelectTitle;
  @JSONField(name: "notification_header")
  String notificationHeader;
  @JSONField(name: "notification_promotion_title")
  String notificationPromotionTitle;
  @JSONField(name: "notification_activity_title")
  String notificationActivityTitle;
  @JSONField(name: "notification_section_title")
  String notificationSectionTitle;
  @JSONField(name: "notification_activity_desc")
  String notificationActivityDesc;
  @JSONField(name: "notification_promotion_desc")
  String notificationPromotionDesc;
  @JSONField(name: "error_dialog_title")
  String errorDialogTitle;
  @JSONField(name: "error_internet")
  String errorInternet;
  @JSONField(name: "error_server_down")
  String errorServerDown;
  @JSONField(name: "error_timeout")
  String errorTimeout;
  @JSONField(name: "error_data_not_found")
  String errorDataNotFound;
  @JSONField(name: "error_not_enough_coins")
  String errorNotEnoughCoins;
  @JSONField(name: "current_language")
  String currentLanguage;
  @JSONField(name: "profile_guest_desc")
  String profileGuestDesc;
  @JSONField(name: "profile_update_password_success")
  String profileUpdatePasswordSuccess;
  @JSONField(name: "profile_create_password_success")
  String profileCreatePasswordSuccess;
  @JSONField(name: "mybooking_title")
  String mybookingTitle;
  @JSONField(name: "mybooking_tab_title_upcoming")
  String mybookingTabTitleUpcoming;
  @JSONField(name: "mybooking_tab_title_history")
  String mybookingTabTitleHistory;
  @JSONField(name: "mybooking_tab_title_favourites")
  String mybookingTabTitleFavourites;
  @JSONField(name: "mybooking_number")
  String mybookingNumber;
  @JSONField(name: "mybooking_empty_text")
  String mybookingEmptyText;
  @JSONField(name: "mybooking_no")
  String mybookingNo;
  @JSONField(name: "mybooking_date")
  String mybookingDate;
  @JSONField(name: "mybooking_coins")
  String mybookingCoins;
  @JSONField(name: "mybooking_menus_all")
  String mybookingMenusAll;
  @JSONField(name: "mybooking_menus_success")
  String mybookingMenusSuccess;
  @JSONField(name: "mybooking_menus_cancel")
  String mybookingMenusCancel;
  @JSONField(name: "mybooking_menus_id")
  String mybookingMenusId;
  @JSONField(name: "mybooking_menus_book_again_button")
  String mybookingMenusBookAgainButton;
  @JSONField(name: "choose_time")
  String chooseTime;
  String venue;
  String appointment;
  String payment;
  @JSONField(name: "booking_successful")
  String bookingSuccessful;
  @JSONField(name: "booking_canceled")
  String bookingCanceled;
  @JSONField(name: "booking_cancel")
  String bookingCancel;
  @JSONField(name: "transaction_date")
  String transactionDate;
  String time;
  String code;
  String fee;
  @JSONField(name: "total_fee")
  String totalFee;
  @JSONField(name: "your_coins")
  String yourCoins;
  @JSONField(name: "booking_status")
  String bookingStatus;
  @JSONField(name: "booking_no")
  String bookingNo;
  String status;
  @JSONField(name: "appointment_date")
  String appointmentDate;
  @JSONField(name: "appointment_time")
  String appointmentTime;
  String confirmation;
  @JSONField(name: "confirmation_booking_cancel")
  String confirmationBookingCancel;
  @JSONField(name: "booking_approved")
  String bookingApproved;
  @JSONField(name: "store_received_your_booking")
  String storeReceivedYourBooking;
  @JSONField(name: "my_coins")
  String myCoins;
  @JSONField(name: "all_history")
  String allHistory;
  String earnings;
  String spendings;
  String topup;
  String apply;
  String reset;
  String popular;
  @JSONField(name: "recommended_events")
  String recommendedEvents;
  String filters;
  @JSONField(name: "topup_coins")
  String topupCoins;
  @JSONField(name: "topup_coins_transfer_money_to_account")
  String topupCoinsTransferMoneyToAccount;
  @JSONField(name: "topup_coins_choose_bank")
  String topupCoinsChooseBank;
  @JSONField(name: "topup_coins_transfer_date")
  String topupCoinsTransferDate;
  @JSONField(name: "topup_coins_date")
  String topupCoinsDate;
  @JSONField(name: "topup_coins_transfer_time")
  String topupCoinsTransferTime;
  @JSONField(name: "topup_coins_amount_of_money")
  String topupCoinsAmountOfMoney;
  @JSONField(name: "topup_coins_amount_of_money_10K")
  String topupCoinsAmountOfMoney10k;
  @JSONField(name: "topup_coins_click_to_select_image")
  String topupCoinsClickToSelectImage;
  @JSONField(name: "topup_coins_upload_payment_slip")
  String topupCoinsUploadPaymentSlip;
  @JSONField(name: "camera_title")
  String cameraTitle;
  @JSONField(name: "photo_library_title")
  String photoLibraryTitle;
  String theme;
  String appointment2;
  @JSONField(name: "no_rating")
  String noRating;
  @JSONField(name: "booking_confirmation")
  String bookingConfirmation;
  @JSONField(name: "add_member_title")
  String addMemberTitle;
  @JSONField(name: "add_member_code")
  String addMemberCode;
  @JSONField(name: "add_member_cardholder_name")
  String addMemberCardholderName;
  @JSONField(name: "add_member_choose_merchant")
  String addMemberChooseMerchant;
  @JSONField(name: "add_member_card_success")
  String addMemberCardSuccess;
  @JSONField(name: "add_member_code_text_field_alert")
  String addMemberCodeTextFieldAlert;
  @JSONField(name: "add_member_card_inactive")
  String addMemberCardInactive;
  @JSONField(name: "add_member_status_waiting")
  String addMemberStatusWaiting;
  @JSONField(name: "add_member_member_code_length")
  String addMemberMemberCodeLength;
  @JSONField(name: "add_member_member_code_check_characters")
  String addMemberMemberCodeCheckCharacters;
  @JSONField(name: "add_member_card_holder_length")
  String addMemberCardHolderLength;
  @JSONField(name: "add_member_card_holder_check_characters")
  String addMemberCardHolderCheckCharacters;
  @JSONField(name: "add_member_card_is_added")
  String addMemberCardIsAdded;
  @JSONField(name: "member_title")
  String memberTitle;
  @JSONField(name: "member_product_value")
  String memberProductValue;
  @JSONField(name: "member_product_deposit")
  String memberProductDeposit;
  @JSONField(name: "member_drink_value")
  String memberDrinkValue;
  @JSONField(name: "member_room_value")
  String memberRoomValue;
  @JSONField(name: "member_product_unit")
  String memberProductUnit;
  @JSONField(name: "member_drink_unit")
  String memberDrinkUnit;
  @JSONField(name: "member_room_unit")
  String memberRoomUnit;
  @JSONField(name: "member_card_expire_in")
  String memberCardExpireIn;
  @JSONField(name: "member_product_total")
  String memberProductTotal;
  @JSONField(name: "member_product_deposit_date")
  String memberProductDepositDate;
  @JSONField(name: "member_history_title")
  String memberHistoryTitle;
  @JSONField(name: "member_history_order_code")
  String memberHistoryOrderCode;
  @JSONField(name: "member_history_price_title")
  String memberHistoryPriceTitle;
  @JSONField(name: "member_history_detail_saller")
  String memberHistoryDetailSaller;
  @JSONField(name: "member_history_detail_order_date")
  String memberHistoryDetailOrderDate;
  @JSONField(name: "member_history_detail_expiration_date")
  String memberHistoryDetailExpirationDate;
  @JSONField(name: "member_history_detail_title")
  String memberHistoryDetailTitle;
  @JSONField(name: "member_history_detail_quantity")
  String memberHistoryDetailQuantity;
  @JSONField(name: "member_history_total_price")
  String memberHistoryTotalPrice;
  @JSONField(name: "member_history_total_currency")
  String memberHistoryTotalCurrency;
  @JSONField(name: "validate_text_field_fill_up_text")
  String validateTextFieldFillUpText;
  @JSONField(name: "validate_text_field_password_text")
  String validateTextFieldPasswordText;
  @JSONField(name: "validate_text_field_password_check_characters_text")
  String validateTextFieldPasswordCheckCharactersText;
  @JSONField(name: "validate_text_field_phone_number_length_text")
  String validateTextFieldPhoneNumberLengthText;
  @JSONField(name: "validate_text_field_phone_number_length_20_text")
  String validateTextFieldPhoneNumberLength20Text;
  @JSONField(name: "validate_text_field_phone_number_invalid_text")
  String validateTextFieldPhoneNumberInvalidText;
  @JSONField(name: "validate_text_field_first_name_length_20_text")
  String validateTextFieldFirstNameLength20Text;
  @JSONField(name: "validate_text_field_first_name_check_characters_text")
  String validateTextFieldFirstNameCheckCharactersText;
  @JSONField(name: "validate_text_field_last_name_length_20_text")
  String validateTextFieldLastNameLength20Text;
  @JSONField(name: "validate_text_field_last_name_check_characters_text")
  String validateTextFieldLastNameCheckCharactersText;
  @JSONField(name: "home_tab_recommend_title")
  String homeTabRecommendTitle;
  @JSONField(name: "home_tab_viewall_title")
  String homeTabViewallTitle;
  String rating;
  @JSONField(name: "give_rating")
  String giveRating;
  String follow;
  String album;
  @JSONField(name: "edit_profile_button")
  String editProfileButton;
  @JSONField(name: "no_following")
  String noFollowing;
  String following;
  String trending;
  String followers;
  @JSONField(name: "follow_btn")
  String followBtn;
  String unfollow;
  @JSONField(name: "yes_or_no")
  String yesOrNo;
  String gallery;
  @JSONField(name: "create_gallery")
  String createGallery;
  @JSONField(name: "create_gallery_success")
  String createGallerySuccess;
  @JSONField(name: "create_gallery_hint")
  String createGalleryHint;
  @JSONField(name: "create_gallery_action")
  String createGalleryAction;
  @JSONField(name: "edit_gallery")
  String editGallery;
  @JSONField(name: "edit_gallery_action")
  String editGalleryAction;
  @JSONField(name: "error_gallery_empty")
  String errorGalleryEmpty;
  @JSONField(name: "error_gallery_name")
  String errorGalleryName;
  @JSONField(name: "add_images")
  String addImages;
  String unpublished;
  String published;
  @JSONField(name: "delete_album")
  String deleteAlbum;
  @JSONField(name: "edit_album_name")
  String editAlbumName;
  @JSONField(name: "confirm_delete_image")
  String confirmDeleteImage;
  @JSONField(name: "confirm_delete_image_desc")
  String confirmDeleteImageDesc;
  @JSONField(name: "confirm_delete_album")
  String confirmDeleteAlbum;
  @JSONField(name: "confirm_delete_album_desc1")
  String confirmDeleteAlbumDesc1;
  @JSONField(name: "confirm_delete_album_desc2")
  String confirmDeleteAlbumDesc2;
  String active;
  String inactive;
  @JSONField(name: "gender_interested")
  String genderInterested;
  @JSONField(name: "select_album_men")
  String selectAlbumMen;
  @JSONField(name: "select_album_female")
  String selectAlbumFemale;
  @JSONField(name: "select_album_all")
  String selectAlbumAll;
  @JSONField(name: "no_trending")
  String noTrending;
  @JSONField(name: "notification_alert_message_type_album")
  String notificationAlertMessageTypeAlbum;
  @JSONField(name: "notification_alert_message_type_user")
  String notificationAlertMessageTypeUser;
  @JSONField(name: "men_model")
  String menModel;
  @JSONField(name: "women_model")
  String womenModel;
  String photographer;
  @JSONField(name: "user_group")
  String userGroup;
  String optional;
  @JSONField(name: "choose_photographer_navigation_title")
  String choosePhotographerNavigationTitle;
  @JSONField(name: "choose_photographer_navigation_type_model_title")
  String choosePhotographerNavigationTypeModelTitle;
  @JSONField(name: "choose_photographer_search_model")
  String choosePhotographerSearchModel;
  @JSONField(name: "choose_photographer_search_photographer")
  String choosePhotographerSearchPhotographer;
  @JSONField(name: "choose_mode_title")
  String chooseModeTitle;
  @JSONField(name: "choose_mode_desc")
  String chooseModeDesc;
  @JSONField(name: "choose_model_female")
  String chooseModelFemale;
  @JSONField(name: "choose_model_male")
  String chooseModelMale;
  @JSONField(name: "choose_model_photographer")
  String chooseModelPhotographer;
  @JSONField(name: "tag_title")
  String tagTitle;
  @JSONField(name: "tag_verify_title")
  String tagVerifyTitle;
  @JSONField(name: "tag_desc")
  String tagDesc;
  @JSONField(name: "choose_from_gallery")
  String chooseFromGallery;
  @JSONField(name: "upload_image")
  String uploadImage;
  @JSONField(name: "choose_image")
  String chooseImage;
  @JSONField(name: "change_album_cover_image")
  String changeAlbumCoverImage;
  String tag;
  @JSONField(name: "create_gallery_text_field_title")
  String createGalleryTextFieldTitle;
  @JSONField(name: "create_add_user_tag_title")
  String createAddUserTagTitle;
  @JSONField(name: "create_add_user_tag_title_photographer")
  String createAddUserTagTitlePhotographer;
  @JSONField(name: "create_add_user_tag")
  String createAddUserTag;
}
