name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ##core
  source_gen: ^0.9.4+4
  json_serializable: ^3.2.2
  json_annotation: ^3.0.0
  shared_preferences: ^0.5.6+1
  intl: ^0.16.0
  provider: ^4.1.1
  cupertino_icons: ^0.1.3
  tix_analytics:
    git:
      url: https://github.com/AsUnDeRz/tix-analytics.git
      ref: master
  tix_navigate :
    git :
      url : https://github.com/AsUnDeRz/tix-navigate.git
      ref: master

  ##Network
  dio: ^3.0.9
  dio_cookie_manager: 1.0.0
  http: ^0.12.1

  ##Device
  devicelocale: ^0.2.0
  package_info: ^0.4.0+17
  device_info: ^0.4.1+4
  device_preview: ^0.4.4

  ##Widget UI
  transparent_image: ^1.0.0
  flutter_rating_bar: ^3.0.1+1
  flutter_time_picker_spinner: ^1.0.6
  flutter_picker: ^1.1.0
  flutter_datetime_picker: ^1.3.4
  flutter_inner_drawer: ^0.5.0
  carousel_slider: ^2.0.0
  material_segmented_control: ^2.0.4
  dotted_border: ^1.0.4
  overlay_support: 1.0.3
  sliding_up_panel: ^1.0.0
  flutter_cupertino_date_picker: ^1.0.24

  ##Utilz
  flutter_statusbarcolor: ^0.2.3
  keyboard_actions: ^3.1.2
  jaguar_jwt: ^2.1.6
  device_id: 0.2.0
  get_ip: ^0.4.0
  cached_network_image: ^2.2.0+1
  mime_type: ^0.3.0
  flutter_svg: ^0.17.4
  image_picker: ^0.6.6
  image_cropper: ^1.0.2
  multi_image_picker:
    git :
      url : https://github.com/tortanoy/multi_image_picker.git
      ref: master

  ##Firebase
  firebase_database: ^3.1.3
  firebase_core: any
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.9

  ##3party
  flutter_facebook_login: ^3.0.0
  sentry: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  ##Inject
  inject:
    git:
      url: https://github.com/AsUnDeRz/inject.dart.git
      path: package/inject
  inject_generator:
    git:
      url: https://github.com/AsUnDeRz/inject.dart.git
      path: package/inject_generator
  build_runner: ^1.7.1
flutter:
  uses-material-design: true
  fonts:
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf
        - asset: fonts/Sarabun-SemiBold.ttf
          weight: 500
        - asset: fonts/Sarabun-Bold.ttf
          weight: 700
  assets:
    - i18n/
    - images/